version: '3.7'

services:
  nest-api:
    container_name: vorlage-api
    image: registry.no749ah.com/vorlage-api:latest
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./config/:/app/config/

  angular-frontend:
    container_name: vorlage-frontend
    image: registry.no749ah.com/vorlage-frontend:latest
    ports:
      - '4200:4200'
    command: >
      bash -c "npm install && ng serve  --configuration production --host 0.0.0.0 --port 4200 --disable-host-check"

networks:
  default:
    external: true
    name: nginx-network
